Core_Proje/Controllers/PortfolioController.cs
using BusinessLayer.Concrete;
using BusinessLayer.ValidationRules;
using DataAccsessLayer.EntityFramework;
using EntityLater.Concrete;
using FluentValidation.Results;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace Core_Proje.Controllers
{
    [Authorize]
    public class PortfolioController : Controller
    {
        PortfolioManager portfolioManager = new PortfolioManager(new EfPortfolioDal());
        public IActionResult Index()
        {
            var values = portfolioManager.TGetList();
            return View(values);
        }
        [HttpGet]
        public IActionResult AddPortfolio()
        {
            return View();
        }
        [HttpPost]
        public IActionResult AddPortfolio(Portfolios portfolios)
        {
            PortfolioValidator validations = new PortfolioValidator();
            ValidationResult results =validations.Validate(portfolios);
            if(results.IsValid)
            {
                portfolioManager.TAdd(portfolios);
                return RedirectToAction("Index");
            }
            else
            {
                foreach(var item in results.Errors)
                {
                    ModelState.AddModelError(item.PropertyName, item.ErrorMessage);
                }
            }
            return View();
        }
        public IActionResult DeletePortfolio(int id)
        {
            var values = portfolioManager.TGetByID(id);
            portfolioManager.TDelete(values);
            return RedirectToAction("Index");
        }
        [HttpGet]
        public IActionResult EditPortfolio(int id)
        {
            var values = portfolioManager.TGetByID(id);
            return View(values);
        }
        [HttpPost]
        public IActionResult EditPortfolio(Portfolios portfolios)
        {
            PortfolioValidator validations = new PortfolioValidator();
            ValidationResult results= validations.Validate(portfolios);
            if(results.IsValid) { 
            portfolioManager.TUpdate(portfolios);
            return RedirectToAction("Index");
            }
            else
            {
                foreach (var item in results.Errors) {
                    ModelState.AddModelError(item.PropertyName, item.ErrorMessage);
                        }
            }
            return View();
        }

    }
}

Core_Proje/Views/Portfolio/AddPortfolio.cshtml
@model EntityLater.Concrete.Portfolios
@{
	ViewData["Title"] = "AddPortfolio";
	Layout = "~/Views/Shared/_NewAdminLayout.cshtml";
}

@using (Html.BeginForm("AddPortfolio", "Portfolio", FormMethod.Post))
{
	<div class="col-12 grid-margin stretch-card">
		<div class="card">
			<div class="card-body">

				<b> <h3 class="card-description"> Yeni Proje Ekleme Paneli </h3></b>
				<form class="forms-sample">
					<b> @Html.Label("Proje Başlığı")</b>
					@Html.TextBoxFor(x => x.Name, new { @class = "form-control" })
					@Html.ValidationMessageFor(x => x.Name)
					<br />
					<label><strong>Görsel 1</strong></label>
					@Html.TextBoxFor(x => x.ImageUrl, new { @class = "form-control" })
					@Html.ValidationMessageFor(x => x.ImageUrl)
					<br />

					<label><strong>Görsel2</strong></label>
					@Html.TextBoxFor(x => x.ImageUrl2, new { @class = "form-control" })
					@Html.ValidationMessageFor(x => x.ImageUrl2)
					<br />

					<label><strong>Proje Url</strong></label>
					@Html.TextBoxFor(x => x.ProjectUrl, new { @class = "form-control" })
					@Html.ValidationMessageFor(x => x.ProjectUrl)
					<br />

					<label><strong>Fiyat</strong></label>
					@Html.TextBoxFor(x => x.Price, new { @class = "form-control" })
					@Html.ValidationMessageFor(x => x.Price)
					<br />

					<label><strong>Tamamlanma Oranı</strong></label>
					@Html.TextBoxFor(x => x.Value, new { @class = "form-control" })
					@Html.ValidationMessageFor(x => x.Value)
					<br />

					<button class="btn btn-success">Kaydet</button>

				</form>
			</div>
		</div>
	</div>
}

Core_Proje/Views/Portfolio/EditPortfolio.cshtml
@model EntityLater.Concrete.Portfolios
@{
	ViewData["Title"] = "EditPortfolio";
	Layout = "~/Views/Shared/_NewAdminLayout.cshtml";
}

@using (Html.BeginForm("EditPortfolio", "Portfolio", FormMethod.Post))
{
	<div class="col-12 grid-margin stretch-card">
		<div class="card">
			<div class="card-body">

				<b> <h3 class="card-description"> Proje Düzenleme Paneli </h3></b>
				<form class="forms-sample">
					<br />
					@Html.HiddenFor(x => x.PortfolioID)

					<b> @Html.Label("Proje Başlığı")</b>
					@Html.TextBoxFor(x => x.Name, new { @class = "form-control" })
					@Html.ValidationMessageFor(x => x.Name)
					<br />
					<label><strong>Görsel 1</strong></label>
					@Html.TextBoxFor(x => x.ImageUrl, new { @class = "form-control" })
					@Html.ValidationMessageFor(x => x.ImageUrl)
					<br />

					<label><strong>Görsel2</strong></label>
					@Html.TextBoxFor(x => x.ImageUrl2, new { @class = "form-control" })
					@Html.ValidationMessageFor(x => x.ImageUrl2)
					<br />

					<label><strong>Proje Url</strong></label>
					@Html.TextBoxFor(x => x.ProjectUrl, new { @class = "form-control" })
					@Html.ValidationMessageFor(x => x.ProjectUrl)
					<br />

					<label><strong>Fiyat</strong></label>
					@Html.TextBoxFor(x => x.Price, new { @class = "form-control" })
					@Html.ValidationMessageFor(x => x.Price)
					<br />

					<label><strong>Tamamlanma Oranı</strong></label>
					@Html.TextBoxFor(x => x.Value, new { @class = "form-control" })
					@Html.ValidationMessageFor(x => x.Value)
					<br />

					<label><strong>Platform</strong></label>
					@Html.TextBoxFor(x => x.Platform, new { @class = "form-control" })
					@Html.ValidationMessageFor(x => x.Platform)
					<br />

					<button class="btn btn-success">Kaydet</button>

				</form>
			</div>
		</div>
	</div>
}

Core_Proje/Views/Portfolio/Index.cshtml
@using EntityLater.Concrete
@model List<Portfolios>
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_NewAdminLayout.cshtml";
}
<div class="row">
    <div class="col">
        <div class="card bg-default shadow">
            <div class="card-header bg-transparent border-0">
                <h3 class="text-white mb-0">Projelerim</h3>
            </div>
            <div class="table-responsive">
                <table class="table align-items-center table-dark table-flush">
                    <thead class="thead-dark">
                        <tr>
                            <th scope="col" class="sort" data-sort="name">Proje</th>
                            <th scope="col" class="sort" data-sort="budget">Ücret</th>
                            <th scope="col" class="sort" data-sort="status">Durum</th>
                            <th scope="col">Görseller</th>
                            <th scope="col" class="sort" data-sort="completion">Tamamlanma Oranı</th>
                            <th scope="col">Sil</th>
                            <th scope="col">Düzenle</th>
                        </tr>
                    </thead>
                    <tbody class="list">
                        @foreach(var item in Model)
                        {
                      
                        <tr>
                            <th scope="row">
                                <div class="media align-items-center">
                                    <a href="#" class="avatar rounded-circle mr-3">
                                            <img alt="Image placeholder" src="@item.Platform">
                                    </a>
                                    <div class="media-body">
                                        <span class="name mb-0 text-sm">@item.Name</span>
                                    </div>
                                </div>
                            </th>
                            <td class="budget">
                                @item.Price
                            </td>
                            <td>
                                <span class="badge badge-dot mr-4">
                                    <i class="bg-success"></i>
                                    <span class="status">Tamamlandı</span>
                                </span>
                            </td>
                            <td>
                                <div class="avatar-group">
                                    <a href="#" class="avatar avatar-sm rounded-circle" data-toggle="tooltip" data-original-title="Ryan Tompson">
                                            <img alt="Image placeholder" src="~/argon-dashboard-master/assets/img/theme/team-1.jpg">
                                    </a>
                                    <a href="#" class="avatar avatar-sm rounded-circle" data-toggle="tooltip" data-original-title="Romina Hadid">
                                            <img alt="Image placeholder" src="~/argon-dashboard-master/assets/img/theme/team-2.jpg">
                                    </a>
                                    <a href="#" class="avatar avatar-sm rounded-circle" data-toggle="tooltip" data-original-title="Alexander Smith">
                                            <img alt="Image placeholder" src="~/argon-dashboard-master/assets/img/theme/team-3.jpg">
                                    </a>
                                    <a href="#" class="avatar avatar-sm rounded-circle" data-toggle="tooltip" data-original-title="Jessica Doe">
                                            <img alt="Image placeholder" src="~/argon-dashboard-master/assets/img/theme/team-4.jpg">
                                    </a>
                                </div>
                            </td>
                            <td>
                                <div class="d-flex align-items-center">
                                    <span class="completion mr-2">@item.Value%</span>
                                    <div>
                                        <div class="progress">
                                                <div class="progress-bar bg-warning" role="progressbar" aria-valuenow="@item.Value%"
                                                     aria-valuemin="0" aria-valuemax="100" style="width:@item.Value%;"></div>
                                        </div>
                                    </div>
                                </div>
                            </td>
                                <td><a href="/Portfolio/DeletePortfolio/@item.PortfolioID" class="btn btn-outline-danger" onclick="return confirm('Silmek istediğinize emin misiniz?');">Sil</a></td>
                                <td><a href="/Portfolio/EditPortfolio/@item.PortfolioID" class="btn btn-outline-warning">Düzenle</a></td>
                        </tr>

                        }
                    </tbody>
                </table>
              
            </div>
           
        </div>
        <br />
        <a href="/Portfolio/AddPortfolio/" class="btn btn-primary">Yeni Proje Ekle</a>
    </div>
  
</div>